### ISSUE TITLE
does not decrease

### ISSUE THREAD

**Issue by seppzzz** [silvershop/silvershop-stock#27]
when having products in a warehouse and a limited stock it doesn't decrease after checkout.
Not good if you sell prototypes having a stock of 1.
SS 4 .2.

**Comment by Greg808** [comment]
Silverstripe Version: 4.3.3
SilvershopVersion: 3.0.0
silvershop/stock: dev-master

It seams it won’t decrement the stock. ProductStockExtension decrementStock() and also the write() method get called. If i watch it with xdebug. I aslo stepped into the write methode but i won't get any errors  it behaves as if it would work but it won’t write to the database. 

I turned on the mysql query log to inspect the query that gets executed. ```Execute    UPDATE "SilverShop_ProductWarehouseStock" SET "ClassName" = 'SilverShop\\Stock\\Model\\ProductWarehouseStock', "LastEdited" = '2019-08-27 13:28:10', "Created" = '2019-08-26 09:44:09', "Quantity" = '98', "ProductID" = 24, "ProductClass" = 'SilverShop\\Page\\Product', "WarehouseID" = 1
WHERE ("ID" = 2)
Close stmt``` Even that looks good to me.

This is how the db table looks like:

![Bildschirmfoto 2019-08-27 um 17 23 53](https://user-images.githubusercontent.com/32903200/63860317-2f326a80-c9a9-11e9-8a66-75c5448759cd.png)

If I can help or provide any further infromation just let me know.

**Comment by Greg808** [comment]
After a fresh install it works as expected. I can't tell why but i think this issue can be closed.
