### ISSUE TITLE
ClassInfo::baseDataClass() no longer exists in SilverStripe 5.2 and is not needed in GridFieldProductStockField

### ISSUE THREAD

**Issue by moritz-sauer-13** [silvershop/silvershop-stock#34]
**Description:** 
In the current version 5.2 of SilverStripe, the method ClassInfo::baseDataClass($record) has been removed. In the GridFieldProductStockField class, this method is called but the result is stored in the variable $base, which is not used anywhere in the handleSave method.

**Issue:** 
The call to ClassInfo::baseDataClass($record) causes an error because this method no longer exists in SilverStripe 5.2. Upon inspection, the result stored in $base is not used in the method, making this call unnecessary.

**Proposed Solution:** 
The call to ClassInfo::baseDataClass($record) should be removed as it serves no purpose in the current context, and $record can be used directly for the required functionality.

**Affected Versions:**
    SilverStripe: 5.2
    Silvershop: dev-main 7e1b330
    Stock: 3.0.0

**Comment by wilr** [comment]
Already fixed in https://github.com/silvershop/silvershop-stock/pull/31
