### ISSUE TITLE
getting the stock for product/variation wrong

### ISSUE THREAD

**Issue by sparkcom** [silvershop/silvershop-stock#5]
In line 106 in ProductStockExension.php 

I changed it to 

` public function getStockForWarehouse($warehouse)
    {
//original line 
        //$record = $warehouse->StockedProducts()->filter('ProductID', $this->owner->ID)->first();
 //new line  
        $record = $warehouse->StockedProducts()->filter( array('ProductID'=> $this->owner->ID, 'ProductClass'=>$this->owner->ClassName ))->first();

...
    }`

**Comment by wilr** [comment]
Thanks!
